### ISSUE TITLE
more than 139 tags?

### ISSUE THREAD

**Issue by yonxie** [nlpaueb/finer#4]
Why is there 279 tags in the feature.names but only 170 id in the 'ner_tag' column? Why do you claim that you only use 139 tags?

**Comment by lefterisloukas** [comment]
This is happening due to the IOB2 encoding scheme. See https://en.wikipedia.org/wiki/Inside%E2%80%93outside%E2%80%93beginning_(tagging) for more.

The XBRL tags are 139. However, ML-wise, we have more tags since each tag might get broken down.

For example the XBRL tag `Revenue` might break down into tags: `B-Revenue` (beginning of Revenue), `I-Revenue` (inside of Revenue), and there is also the universal `O` tag which means that this token is not any entity.
